version: '3'
services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - elixir-deps:/app/deps
      - elixir-build:/app/_build
      - node-modules:/assets/node_modules
    tty: true
    stdin_open: true
    ports:
      - "4000:4000"
volumes:
  elixir-deps:
  elixir-build:
  node-modules:
